### ISSUE TITLE
rake fails

### ISSUE THREAD

**Issue by h4ck3rm1k3** [MikeSofaer/vanna#3]
rake, version 0.8.7

``` ruby
(in /home/mdupont/experiments/diaspora/deps/vanna)
** Invoke default (first_time)
** Invoke test (first_time)
** Execute test
ruby test/basic_test.rb
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- wrong (LoadError)
    from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from /var/lib/gems/1.8/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:596:in `new_constants_in'
    from /var/lib/gems/1.8/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /var/lib/gems/1.8/gems/activesupport-3.0.7/lib/active_support/dependencies.rb:239:in `require'
    from ./test/test_helper.rb:7
    from test/basic_test.rb:1:in `require'
    from test/basic_test.rb:1
rake aborted!
Command failed with status (1): [ruby test/basic_test.rb...]
/usr/lib/ruby/1.8/rake.rb:995:in `sh'
/usr/lib/ruby/1.8/rake.rb:1010:in `call'
/usr/lib/ruby/1.8/rake.rb:1010:in `sh'
/usr/lib/ruby/1.8/rake.rb:1094:in `sh'
/home/mdupont/experiments/diaspora/deps/vanna/Rakefile:5
/usr/lib/ruby/1.8/rake.rb:636:in `call'
/usr/lib/ruby/1.8/rake.rb:636:in `execute'
/usr/lib/ruby/1.8/rake.rb:631:in `each'
/usr/lib/ruby/1.8/rake.rb:631:in `execute'
/usr/lib/ruby/1.8/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:607:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:604:in `each'
/usr/lib/ruby/1.8/rake.rb:604:in `invoke_prerequisites'
/usr/lib/ruby/1.8/rake.rb:596:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:583:in `invoke'
/usr/lib/ruby/1.8/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2029:in `each'
/usr/lib/ruby/1.8/rake.rb:2029:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2023:in `top_level'
/usr/lib/ruby/1.8/rake.rb:2001:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28
```

**Comment by MikeSofaer** [comment]
Interesting.  Did you bundle install?  It looks like you don't have wrong, which is in the .gemspec

**Comment by h4ck3rm1k3** [comment]
well when I use the rake and bundle it works, or at least does not complain,. but standalone, it does not. I noticed this problem with many of the diaspora dependencies, the standalone rake just fails.

**Comment by MikeSofaer** [comment]
Ahh.  Well, needing to bundle install before you rake is standard practice in the Ruby world these days.  A case could certainly be made that it should work out of the box, but I think that's probably bigger than this project.  Since bundling fixes this, closing the issue.

**Comment by h4ck3rm1k3** [comment]
Ok, I am still trying to do this.
having problems (/home/mdupont/.rvm/gems/ruby-1.9.2-p290/gems/turn-0.8.3/lib/turn/autorun/minitest.rb:14:in `<top (required)>': MiniTest v1.6.0 is out of date. (RuntimeError)
`gem install minitest`and add`gem 'minitest' to you test helper.
)
 Will continue tomorrow and report back.

**Comment by h4ck3rm1k3** [comment]
I have pushed my patches to :
To git@github.com:h4ck3rm1k3/vanna.git
   334eec2..9879a33  master -> master

Still not passing all the tests, there are dependancies on Diaspora code, will make mockups for them. 
https://github.com/h4ck3rm1k3/vanna

when all test pass,will make a push request.

**Comment by h4ck3rm1k3** [comment]
The problem still occurs and is fixed by my patches. reopening. 

mdupont@space-station:~/experiments/diaspora_deps$ git clone https://github.com/MikeSofaer/vanna.git vanna_orig
Initialized empty Git repository in /home/mdupont/experiments/diaspora_deps/vanna_orig/.git/
cremote: Counting objects: 610, done.
remote: Compressing objects: 100% (280/280), done.
remote: Total 610 (delta 291), reused 592 (delta 273)
Receiving objects: 100% (610/610), 146.51 KiB, done.
Resolving deltas: 100% (291/291), done.
mdupont@space-station:~/experiments/diaspora_deps$ cd vanna_orig/
mdupont@space-station:~/experiments/diaspora_deps/vanna_orig$ rvm do rake 
ruby test/basic_test.rb
/home/mdupont/.rvm/gems/ruby-1.9.2-p290/gems/rack-1.3.4/lib/rack/backports/uri/common_192.rb:53: warning: already initialized constant WFKV_
/home/mdupont/.rvm/gems/ruby-1.9.2-p290/gems/turn-0.8.3/lib/turn/autorun/minitest.rb:14:in `<top (required)>': MiniTest v1.6.0 is out of date. (RuntimeError)
`gem install minitest`and add`gem 'minitest' to you test helper.
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from /home/mdupont/.rvm/gems/ruby-1.9.2-p290/gems/turn-0.8.3/lib/turn.rb:13:in `<top (required)>'
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in`require'
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in `rescue in require'
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in`require'
    from /home/mdupont/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.1/lib/rails/test_help.rb:19:in `<top (required)>'
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /home/mdupont/experiments/diaspora_deps/vanna_orig/test/test_helper.rb:5:in`<top (required)>'
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from test/basic_test.rb:1:in `<main>'
rake aborted!
Command failed with status (1): [ruby test/basic_test.rb...]

Tasks: TOP => default => test
(See full trace by running task with --trace)
ruby test/basic_test.rb
You are using an outdated version of Test::Unit.
Make sure to use Bundler or Rubygems to load the test-unit gem. For example:
  require 'rubygems'
  gem 'test-unit'
  require 'test/unit'
  require 'wrong/adapters/test_unit'
rake aborted!
Command failed with status (1): [ruby test/basic_test.rb...]

Tasks: TOP => default => test
(See full trace by running task with --trace)
mdupont@space-station:~/experiments/diaspora_deps/vanna_orig$ rvm do bundle install
Using rake (0.9.2) 
Using ZenTest (4.4.1) 
Using RubyInline (3.8.6) 
Using sexp_processor (3.0.5) 
Using ParseTree (3.0.6) 
Using abstract (1.0.0) 
Using activesupport (3.0.3) 
Using builder (2.1.2) 
Using i18n (0.6.0) 
Using activemodel (3.0.3) 
Using erubis (2.6.6) 
Using rack (1.2.1) 
Using rack-mount (0.6.14) 
Using rack-test (0.5.6) 
Using tzinfo (0.3.30) 
Using actionpack (3.0.3) 
Using mime-types (1.16) 
Using polyglot (0.3.2) 
Using treetop (1.4.10) 
Using mail (2.2.19) 
Using actionmailer (3.0.3) 
Using arel (2.0.10) 
Using activerecord (3.0.3) 
Using activeresource (3.0.3) 
Using bundler (1.0.21) 
Using diff-lcs (1.1.2) 
Using spruz (0.2.2) 
Using file-tail (1.0.5) 
Using json (1.6.1) 
Using predicated (0.2.2) 
Using thor (0.14.6) 
Using railties (3.0.3) 
Using rails (3.0.3) 
Using ruby_parser (2.0.5) 
Using ruby2ruby (1.2.5) 
Using sourcify (0.4.0) 
Using vanna (0.1.1) from source at . 
Using wrong (0.5.0) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
Using rake (0.9.2) 
Using ZenTest (4.4.1) 
Using RubyInline (3.8.6) 
Using sexp_processor (3.0.5) 
Using ParseTree (3.0.6) 
Using abstract (1.0.0) 
Using activesupport (3.0.3) 
Using builder (2.1.2) 
Using i18n (0.6.0) 
Using activemodel (3.0.3) 
Using erubis (2.6.6) 
Using rack (1.2.1) 
Using rack-mount (0.6.14) 
Using rack-test (0.5.6) 
Using tzinfo (0.3.30) 
Using actionpack (3.0.3) 
Using mime-types (1.16) 
Using polyglot (0.3.2) 
Using treetop (1.4.10) 
Using mail (2.2.19) 
Using actionmailer (3.0.3) 
Using arel (2.0.10) 
Using activerecord (3.0.3) 
Using activeresource (3.0.3) 
Using bundler (1.0.21) 
Using diff-lcs (1.1.2) 
Using spruz (0.2.2) 
Using file-tail (1.0.5) 
Using json (1.6.1) 
Using predicated (0.2.2) 
Using thor (0.14.6) 
Using railties (3.0.3) 
Using rails (3.0.3) 
Using ruby_parser (2.0.5) 
Using ruby2ruby (1.2.5) 
Using sourcify (0.4.0) 
Using vanna (0.1.1) from source at . 
Using wrong (0.5.0) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
mdupont@space-station:~/experiments/diaspora_deps/vanna_orig$ rvm do rake 
ruby test/basic_test.rb
/home/mdupont/.rvm/gems/ruby-1.9.2-p290/gems/rack-1.3.4/lib/rack/backports/uri/common_192.rb:53: warning: already initialized constant WFKV_
/home/mdupont/.rvm/gems/ruby-1.9.2-p290/gems/turn-0.8.3/lib/turn/autorun/minitest.rb:14:in `<top (required)>': MiniTest v1.6.0 is out of date. (RuntimeError)
`gem install minitest`and add`gem 'minitest' to you test helper.
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from /home/mdupont/.rvm/gems/ruby-1.9.2-p290/gems/turn-0.8.3/lib/turn.rb:13:in `<top (required)>'
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in`require'
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in `rescue in require'
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in`require'
    from /home/mdupont/.rvm/gems/ruby-1.9.2-p290/gems/railties-3.1.1/lib/rails/test_help.rb:19:in `<top (required)>'
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in`require'
    from /home/mdupont/.rvm/rubies/ruby-1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:55:in `require'
    from /home/mdupont/experiments/diaspora_deps/vanna_orig/test/test_helper.rb:5:in`<top (required)>'
    from internal:lib/rubygems/custom_require:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in`require'
    from test/basic_test.rb:1:in `<main>'
rake aborted!
Command failed with status (1): [ruby test/basic_test.rb...]

Tasks: TOP => default => test
(See full trace by running task with --trace)
ruby test/basic_test.rb
You are using an outdated version of Test::Unit.
Make sure to use Bundler or Rubygems to load the test-unit gem. For example:
  require 'rubygems'
  gem 'test-unit'
  require 'test/unit'
  require 'wrong/adapters/test_unit'
rake aborted!
Command failed with status (1): [ruby test/basic_test.rb...]

Tasks: TOP => default => test
(See full trace by running task with --trace)
mdupont@space-station:~/experiments/diaspora_deps/vanna_orig$

**Comment by h4ck3rm1k3** [comment]
https://github.com/MikeSofaer/vanna/pull/4 I created a pull request patch for you.
